[workspace]
members = [
	"wnfs",
	"wnfs-bench",
	"wnfs-common",
	"wnfs-hamt",
	"wnfs-nameaccumulator",
	"wnfs-unixfs-file",
	"wnfs-wasm",
]

# Speedup build on macOS
# See https://blog.rust-lang.org/2021/03/25/Rust-1.51.0.html#splitting-debug-information
[profile.dev]
split-debuginfo = "unpacked"
